
GET http://localhost:4000/login

Content-Type: application/json
{
   "email":"astranovajknkjkknsta@g.com",
   "password":"123123123"
}

###
POST http://localhost:4000/register


Content-Type: application/json
{
   "email":"astranovajknkjkknsta@g.com",
   "password":"123123123"
}